baseURL = 'https://modestwalrus.com/'
languageCode = 'en-us'
title = 'Modest Walrus'
theme = 'mana'

[params]
  description = "Gaming 🎮 AND Music 🎵"

[params.avatar]
  url = '/walrus.png'

[[menus.main]]
  name = "About"
  url = "/about/"
  weight = 1

[[menus.main]]
  name = "Gaming"
  url = "/gaming/"
  weight = 2

[[menus.main]]
  name = "Music"
  url = "/music/"
  weight = 3
