baseURL = 'https://modestwalrus.com/'
languageCode = 'en-us'
title = 'Modest Walrus'
theme = 'mana'
enableEmoji = true
enableRobotsTXT = true

[params]
  heroSubtitle = ["Gaming AND Music", "(1-100 Point System)"]
  description = "Modest Walrus is a gaming and music review site. Games and albums rated on a 1-100 point system."
  author = "Modest Walrus"

[params.avatar]
  url = '/walrus.png'

[[menus.main]]
  name = "About"
  url = "/about/"
  weight = 1

[[menus.main]]
  name = "Gaming"
  url = "/gaming/"
  weight = 2

[[menus.main]]
  name = "Music"
  url = "/music/"
  weight = 3
